spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

authservice:
  base-url: ${AUTHSERVICE_BASE_URL:http://host.docker.internal:8082}

userservice:
  base-url: ${USERSERVICE_BASE_URL:http://host.docker.internal:8081}
